# Generated by Django 4.2.3 on 2023-07-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
