# Generated by Django 4.2.3 on 2023-07-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='user_id',
        ),
    ]
