# Generated by Django 4.2.2 on 2023-06-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method',
            new_name='payment_methods',
        ),
    ]
