# Generated by Django 4.2.3 on 2023-07-10 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_rename_user_customer_user_id'),
        ('payment', '0003_rename_payment_method_payment_payment_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='name',
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
    ]
