# Generated by Django 4.2.2 on 2023-06-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Sender_name',
            new_name='Recievers_Name',
        ),
    ]
