# Generated by Django 3.2.12 on 2023-08-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_rename_sender_name_notification_recievers_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Recievers_Name',
            new_name='recievers_Name',
        ),
    ]
