# Generated by Django 4.2.2 on 2023-06-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_updated',
        ),
    ]
