# Generated by Django 4.2.3 on 2023-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Portname', models.CharField(max_length=32)),
                ('Date_shipment_placed', models.DateTimeField()),
                ('Date_shipment_recieved', models.DateTimeField()),
                ('Product', models.CharField(max_length=20)),
                ('Delivery_person', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
