# Generated by Django 4.2.3 on 2023-07-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_payment'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='Portname',
            new_name='Location',
        ),
        migrations.AddField(
            model_name='shipment',
            name='orders',
            field=models.ManyToManyField(to='orders.orders'),
        ),
    ]
