# Generated by Django 4.2.3 on 2023-07-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment',
        ),
    ]
