# Generated by Django 4.2.3 on 2023-07-10 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0006_alter_orders_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
